### PR TITLE
graphql-php v15

### PR DESCRIPTION
**Pull request by bladl**
We have 23 test errors after bumping webonyx version
https://github.com/thecodingmachine/graphqlite/issues/540

### CODE REVIEW

**Comment by bladl** [comment]
@oojacoboo Minimum supported php version for ecodev/graphql-upload is ^8.1. But we have continuous integration for php 8.0

**Comment by bladl** [comment]
Other test errors I will try to fix by myself

**Comment by bladl** [comment]
There was a bunch of breaking changes. 
Finally, all php >8.0 tests passed. Please review a PR !

**Comment by oojacoboo** [comment]
Dropped 8.0 tests.  I'll review the rest of the PR soon.

**Comment by bladl** [comment]
Does it means we drop support for php 8.0? So we can use all range of php 8.1 features from now

**Comment by oojacoboo** [comment]
Yes, we'd basically be dropping 8.0 support and only supporting >=8.1 with this PR.  However, I am wondering why `ecodev/graphql-upload` has minimum 8.1 support.

Also, I didn't check.  What were the test errors surrounding 8.0?

**Comment by bladl** [comment]
> 
> 
> Also, I didn't check.  What were the test errors surrounding 8.0?

composer install failed so I did not run tests in php 8.0 enviroment.

**Comment by bladl** [comment]
While I was working for this and previous PR I felt a huge lack of native PHP [intersection types](https://php.watch/versions/8.1/intersection-types). Many docblocks and assertions can be dropped with php 8.1. 

With all range of php 8.1 features debugging codebase would be much simpler and I believe graphqlite will evolve much faster.
In my opinion it's worth to drop support for php 8.0 now in any case.

**Pull request merged**
