### PR TITLE
Replaces the abandoned package Zend\Diactoros to Laminas\Diactoros

### PR DESCRIPTION
**Pull request by gpupo**
This replaces the abandoned zend/diactoros package with the new community-supported laminas/diactoros

### CODE REVIEW

**Comment by moufmouf** [comment]
Excellent! Thanks a lot. I'll keep this open until I find some time to fix the tests (https://travis-ci.org/github/thecodingmachine/graphqlite/jobs/684212627), but definitely a big thanks as this was on my todo list for quite some time :)

For some reason, Travis tests are not appearing here, I'll have to figure out why.

**Comment by gpupo** [comment]
hi @moufmouf ! 
I tried to understand the failure of your test but I was not successful. I am not familiar with the syntax of phpstan. Could you open this issue explaining the problem so that we can help you with that?

**Comment by moufmouf** [comment]
The error was unrelated to your change but simply due to a new PHPStan release that found additional bugs.
I fixed this in master.
Could you simply rebase your branch? This should trigger again the CI that will hopefully pass.

Sorry for the delay!

**Comment by gpupo** [comment]
Ok @moufmouf , branch rebased

**Comment by moufmouf** [comment]
Almost! One minor issue in the CI and we are good to go (it's the Doctrine coding standard being a bit strict :) )

```
----------------------------------------------------------------------

FOUND 1 ERROR AFFECTING 1 LINE

----------------------------------------------------------------------

 16 | ERROR | [x] Use statements should be sorted alphabetically. The

    |       |     first wrong one is

    |       |     Laminas\Diactoros\ResponseFactory.

    |       |     (SlevomatCodingStandard.Namespaces.AlphabeticallySortedUses.IncorrectlyOrderedUses)

----------------------------------------------------------------------

PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY

----------------------------------------------------------------------
```

Simply run "composer cs-fix" and push the modified files and we are good to go!

**Comment by gpupo** [comment]
fixed

**Comment by moufmouf** [comment]
Thanks so much!

**Comment by gpupo** [comment]
@moufmouf do you want to setup php-cs-fixer in the project ?

**Comment by moufmouf** [comment]
Ho no, thanks. We are already using "doctrine/coding-standard" which is using "php codesniffer" under the hood (which is a competitor to php-cs-fixer).
Both solutions work great, but "doctrine/coding-standard" is quite amazing at being extremely strict (stricter in my experience than what you can get with php-cs-fixer)

**Pull request merged**
