### PR TITLE
Add config example with PHP 8 attributes to input types docs

### PR DESCRIPTION
**Pull request by andrew-demb**
Unfortunately, I don't know how to check the built result.

Copied tabs markup from example from the same page

### CODE REVIEW

**Comment by oojacoboo** [comment]
@andrew-demb thank you for these efforts.  We're overdue for a release.  However, I believe you can check the "Next" version on the docs to see attribute examples that have already been added/updated.

**Comment by oojacoboo** [comment]
We could merge this though, if you'd like to confirm.  On your local machine, you can run `npm run serve` I believe it is and it'll run an npm server with the built docs.

**Comment by andrew-demb** [comment]
Fixed introduced inconsistency between annotation and attribute example.

I can confirm result is displayed correctly.
Should I add the same changes to all versioned docs too (as of now it is applied only for the 'next' release)?

<details>
  <summary>Screenshot</summary>

image
</details>

**Comment by oojacoboo** [comment]
@andrew-demb Thanks.  You could also update for >= 4.1 archives as well.  I believe, 4.1 was the first version to support attributes.

**Comment by andrew-demb** [comment]
Checked and done.
Thanks for your help.

**Pull request merged**
