### PR TITLE
Fix use of MagicField with phpType on a proxy class without magic __get method

### LINKED ISSUE #404: MagicField with phpType on a proxy class without magic __get method
When there is a proxy class for source class with __get method, and proxy class has MagicField with phpType set, the exception is thrown "ReflectionException: Method __get does not exist". This is because of the line `$refMethod = $refClass->getMethod('__get');`, where `$refClass` points to the proxy class, which does not have this method.

### PR DESCRIPTION
**Pull request by michael-vostrikov**
Closes #404

### CODE REVIEW

**Comment by oojacoboo** [comment]
This probably needs to be handled some other way.  Currently, as it's written, if there isn't a `__get` magic method, instead of failing, it's simply assigning `null`.  It's better to fail than to assign something that wasn't intended.

Can you please outline your proxy class example here?

**Comment by michael-vostrikov** [comment]
It is like in test, just a proxy class with MagicField with phpType.
https://github.com/thecodingmachine/graphqlite/pull/405/files#diff-95511f6323fe084d6ab0e77ef3c9c71b20247b1e26c34c0e1d7b0bcf5880d4d0

`$refMethod` is required in `resolvePhpType()` and `mapReturnType()`, so it should be some real method. The right way would be using a `__get()` mehtod from source class, but it is not passed into `getQueryFieldsFromSourceFields()`. Anyway it is used as a stub, real type is taken from `$phpTypeStr`, so I thought a fake method would be good enough.

**Comment by oojacoboo** [comment]
Okay, so after reviewing a bit more, I think I see what you're doing here.  This is an extended type class, right?  It's not exactly a "proxy class"?  Assuming I'm understanding your intent properly, I don't have an issue with getting a proper fix for this use case.  However, the current implementation is quite bad.

Firstly, nested if statements are a big red flag.  But more importantly, the `if (! $sourceField->shouldFetchFromMagicProperty())` evaluation should be returning `false`, letting the magic property logic handle the assignment.

The submitted code hacks something into place that happens to work for your use case.  We need something that works with the existing logic.

**Comment by michael-vostrikov** [comment]
> This is an extended type class, right?

 No, according to [documentation](https://graphqlite.thecodingmachine.io/docs/external-type-declaration#sourcefield-annotation), `TestTypeWithMagicPropertyType` is a proxy class for `TestTypeWithMagicProperty`, just instead of `SourceField` I use `MagicField`.
 
> We need something that works with the existing logic.

Existing logic contains a bug, pull request fixes it. Try to comment changes in `FieldsBuilder` and run the test. You will get PHP exception "ReflectionException: Method __get does not exist", though by documentation this is a valid construction. It works with `MagicField(outputType)` but does not with `MagicField(phpType)`.

**Comment by oojacoboo** [comment]
@michael-vostrikov thanks for the clarity.  Regarding the changes, my comments remain the same.  The existing logic may not work in this case, which I understand.  However, your changes are a hack, and not a good one.  The changes need to be worked into the existing logic in a better way, as I described.

**Comment by michael-vostrikov** [comment]
Found a way how to get source class and magic __get method in it.

**Comment by oojacoboo** [comment]
@michael-vostrikov this is much better!  Can we find a more appropriate method name for `findMagicGetMethodContainer`?  Maybe something like `getRefClassOrProxy`?  Also, it's best to use the conditional check, `if (! $controllerRefClass->hasMethod('__get'))` with an early return.  This keeps the code cleaner.

**Comment by michael-vostrikov** [comment]
I did it a little wrong, `$refClass` should always be a proxy class, because it's where we write class name in phpType, and where we can write `use` for this class. There may not be this `use` in a source class. So the method name now is `getMagicGetMethodFromSourceClassOrProxy`.

**Comment by oojacoboo** [comment]
This looks great @michael-vostrikov.  Thanks for the PR and the follow-up work on it!

**Pull request merged**
