### PR TITLE
Adding CakePHP plugin interweberde/cakephp-graphql

### PR DESCRIPTION
**Pull request by challgren**
During CakeFest2022 @xyng introduced a plugin for CakePHP

### CODE REVIEW

**Comment by oojacoboo** [comment]
Awesome!  It'd be nice if the README included something giving a little more confidence to potential users.  It reads more like... we make no guarantees, might not receive any support and might not work, and it takes quite a bit to get up and running.

I'd really like to see a little more commitment here to the plugin.  Can that be done?

**Comment by challgren** [comment]
I was only a participant during CakeFest so I can't say for sure about more commitment etc... But personally I'm going to try to reverse engineer it and learn it that way since it was just released hours ago, unplanned. I'm sure more docs will become available once the video of the session is done. And I'm sure the core developer is going to improve the docs, the code was previously closed source and was opened at the request of the community.

**Comment by xyng** [comment]
Hey @oojacoboo and @challgren - I just found the thread here :-)
The Plugin has been cooking internally about 2,5 years now and after my talk at CakeFest this Friday I way encouraged to open-source it.
As that was rather spontaneous so that people could have a first quick glance at it, I spun up a readme that is more on the "defensive" side.
Once my project-load allows me to care about documentation and examples, those will land there.
Until then I feel better telling potential users that the state of the project is currently uncertain.

**Comment by xyng** [comment]
I totally agree!

**Comment by challgren** [comment]
I'll close this PR until the plugin gets more stable.

**Pull request closed without merging**
