### PR TITLE
Suggest xkojimedia/laravel-altair-graphql package

### PR DESCRIPTION
**Pull request by imolorhe**
Suggest [xkojimedia/laravel-altair-graphql](https://github.com/XKojiMedia/laravel-altair-graphql) as another GraphQL dev tool that can be used to display a UI.

### CODE REVIEW

**Comment by moufmouf** [comment]
Hey Samuel,

Thanks a lot for this pull request. Let me just test this new package and I'll merge this.
In the meantime, you might want to this file: https://github.com/thecodingmachine/graphqlite/blob/master/website/versioned_docs/version-4.0/laravel-package.md

The doc that you modified is the doc for "master" that will only be online with v4.1 is released. If you want your change to be visible right now, you need to also modify the doc in the website/versioned_docs/version-4.0/ directory.

Anyway, thanks a lot for the PR.

I also have a question. Do you know if there are any similar package that adds Altair to Symfony?

**Comment by imolorhe** [comment]
Hey! Thanks.

I'm not aware of a similar package for Symfony. I could consider looking into that next 🙂

**Comment by imolorhe** [comment]
There's now a symfony package for altair 🙂 https://packagist.org/packages/xkojimedia/altair-graphql-symfony-bundle

**Comment by moufmouf** [comment]
> There's now a symfony package for altair slightly_smiling_face https://packagist.org/packages/xkojimedia/altair-graphql-symfony-bundle

Woot! Excellent!

I'm having some trouble accessing Altair using your package. I opened an issue here:

https://github.com/XKojiMedia/laravel-altair-graphql/issues/1

I'll merge this when the issue is solved.

**Pull request merged**
