### PR TITLE
patch: drop DoctrineAnnotations

### PR DESCRIPTION
**Pull request by fogrye**
BC: AnnotationReader constructor changed and it's methods stops triggering exceptions

TestControllerWithInvalidParameterAnnotation deleted as `for` is ignored when `HideParameter` used as parameter attribute

Also attribute exceptions and classes polished

Fixes: #675

### CODE REVIEW

**Review by oojacoboo — CHANGES_REQUESTED** [review]
Thanks again for this PR!  I've finished reviewing it - just some small changes.

**Comment by fogrye** [comment]
@oojacoboo I marked this PR as draft because I though it would be nice to fix documentation with it (and remove php7 examples as we do not support it). Or I can have make that in separate PR. What is better for you?

**Comment by oojacoboo** [comment]
> @oojacoboo I marked this PR as draft because I though it would be nice to fix documentation with it (and remove php7 examples as we do not support it). Or I can have make that in separate PR. What is better for you?

Agreed.  Let's update the docs in this PR.

**Comment by oojacoboo** [comment]
@fogrye thanks for the docs updates.  I think we should go ahead and update the [Annotations Reference](https://graphqlite.thecodingmachine.io/docs/annotations-reference) for attributes and drop the "annotations" name.  So the list of attributes are no longer `@whatever`, but `#[whatever]` or `whatever`.

**Review by oojacoboo — APPROVED** [review]

**Pull request merged**
