### PR TITLE
Preserve type already added

### PR DESCRIPTION
**Pull request by fezfez**
Hello,

With this PR this code will preserve MyCustomInputType

```php
        $factory = new SchemaFactory();
        $factory->setSchemaConfig(SchemaConfig::create([
            'types' => [
                MyCustomInputType::getInstance()
            ]
        ]));

       $schema = $factory->createSchema();
```

### CODE REVIEW

**Comment by fezfez** [comment]
Is this a good approach ? if it seem to good to you i will fix the tests, otherwise can you provide a good way to do this ?

**Comment by oojacoboo** [comment]
@fezfez Can you describe in a bit more detail what it is you're hoping to accomplish here?  What's the design challenge you're having in your API?  Is it that you're basically wanting a static type?  Assuming so, I don't see any point in doing this, as opposed to just programming an input to be static itself.

**Comment by fezfez** [comment]
@oojacoboo i have created a very lite sample of my problem at https://github.com/fezfez/sample-graphqlite

**Comment by oojacoboo** [comment]
@fezfez , would it be possible to get an explanation of your intended goals here as well?  I can see from the code you're trying to create custom types using the webonyx API.  But why?  Can you explain why you cannot use a normal annotated object, or what the overall goal is?

**Comment by oojacoboo** [comment]
Closing unless this is still needed.

**Pull request closed without merging**
