### PR TITLE
Codebase improvements with php 8.1 features

### PR DESCRIPTION
**Pull request by bladl**
Commit https://github.com/thecodingmachine/graphqlite/commit/79536382c287ffa8e04f2dda663f20a48e65bca5 allows us to use all range of php 8.1 features.
I tried to improve some code.

There is list of changes:
- convert `switch` to `match` syntax
- `final` keyword for internal classes
- add `readonly` modifier to private class properties
- replace phpdoc intersection type (e.g.  `GraphQLType&OutputType` ) with native. (Can be BREAKING for some specific external usage)
- bump phpstan version. Version 1.9 contains fixes for php 8.1 such as https://github.com/phpstan/phpstan/issues/5906

### CODE REVIEW

**Comment by bladl** [comment]
@oojacoboo Is doc generation failed due to auto bumping `@docusaurus/preset-classic` in https://github.com/thecodingmachine/graphqlite/pull/539 ?

**Comment by oojacoboo** [comment]
@bladl I've updated docusaurus.  Please try merging origin into your fork.

**Comment by bladl** [comment]
@oojacoboo now all checks are passed

**Review by oojacoboo — APPROVED** [review]

**Comment by oojacoboo** [comment]
@bladl thanks for this - merged in!

**Pull request merged**
